/**
 * assemble.js — Reads scene JSONs + audio metadata, outputs computed SCENES array.
 * Uses shared.js for word-boundary timing resolution.
 */
const fs = require('fs');
const path = require('path');
const { loadMetadata, T, actionsToJS, LEAD_MS, estimateClipDuration } = require('./shared');

const SCENE_DIR = path.join(__dirname, 'scenes');
const AUDIO_DIR = path.join(__dirname, '..', 'audio_scenes');
const OUT_FILE = path.join(__dirname, '..', 'scenes-compiled.js');

// Load all metadata
const meta = loadMetadata(AUDIO_DIR);

// Load scene files in order
const sceneFiles = fs.readdirSync(SCENE_DIR)
  .filter(f => f.endsWith('.json'))
  .sort();

const compiledScenes = [];

for (const file of sceneFiles) {
  const scene = JSON.parse(fs.readFileSync(path.join(SCENE_DIR, file), 'utf-8'));
  const clips = scene.clips || [];

  // Compute total scene duration from clips
  let duration = 0;
  for (const clip of clips) {
    if (typeof clip === 'string') {
      duration += estimateClipDuration(meta, clip);
    } else if (clip && clip.pause) {
      duration += clip.pause;
    }
  }

  // Resolve triggers
  const triggers = [];
  for (const trigger of (scene.triggers || [])) {
    let delay = 0;
    const anchor = trigger.anchor;

    if (anchor.fixed !== undefined) {
      delay = anchor.fixed;
    } else if (anchor.clip && anchor.word) {
      const nth = anchor.n || 1;
      const resolved = T(meta, clips, anchor.clip, anchor.word, nth);
      if (resolved < 0) {
        console.warn(`  ⚠ Word "${anchor.word}" (n=${nth}) not found in clip "${anchor.clip}" — using 0`);
        delay = 0;
      } else {
        delay = resolved;
      }
    }

    const js = actionsToJS(trigger.actions);
    triggers.push({ delay, js });
  }

  // Sort triggers by delay
  triggers.sort((a, b) => a.delay - b.delay);

  compiledScenes.push({
    id: scene.scene,
    title: scene.title,
    clips,
    duration,
    triggers
  });

  console.log(`✓ ${scene.scene} "${scene.title}" — ${clips.length} clips, ${triggers.length} triggers, ${Math.round(duration)}ms`);
}

// Write output
const output = `// Auto-generated by assemble.js — do not edit
const SCENES = ${JSON.stringify(compiledScenes, null, 2).replace(/"js":\s*"([^"]*)"/g, '"run": function() { $1 }')};
`;

fs.writeFileSync(OUT_FILE, output, 'utf-8');
console.log(`\n✅ Wrote ${sceneFiles.length} scenes to ${OUT_FILE}`);
