/**
 * build-video.js — Bakes audio (base64) + word metadata + compiled scenes
 * into click-done-video.html → click-done-video-final.html
 */
const fs = require('fs');
const path = require('path');

const HTML_SRC = path.join(__dirname, 'click-done-video.html');
const SCENES_SRC = path.join(__dirname, 'scenes-compiled.js');
const AUDIO_DIR = path.join(__dirname, 'audio_scenes');
const HTML_OUT = path.join(__dirname, 'click-done-video-final.html');

// 1. Read source HTML
let html = fs.readFileSync(HTML_SRC, 'utf-8');

// 2. Read compiled scenes JS
const scenesJS = fs.readFileSync(SCENES_SRC, 'utf-8');

// 3. Build audio data (base64-encoded mp3)
const audioData = {};
const wordMeta = {};
const audioFiles = fs.readdirSync(AUDIO_DIR).filter(f => f.endsWith('.mp3'));

for (const af of audioFiles) {
  const clipName = af.replace('.mp3', '');
  const mp3Buf = fs.readFileSync(path.join(AUDIO_DIR, af));
  audioData[clipName] = 'data:audio/mp3;base64,' + mp3Buf.toString('base64');

  // Load corresponding metadata
  const metaFile = path.join(AUDIO_DIR, clipName + '.metadata.json');
  if (fs.existsSync(metaFile)) {
    const raw = JSON.parse(fs.readFileSync(metaFile, 'utf-8'));
    wordMeta[clipName] = (raw.Metadata || [])
      .filter(m => m.Type === 'WordBoundary')
      .map(m => ({
        t: Math.round(m.Data.Offset / 10000),
        d: Math.round(m.Data.Duration / 10000),
        w: m.Data.text.Text
      }));
  }
}

console.log(`📦 Packed ${Object.keys(audioData).length} audio clips`);
console.log(`📋 Packed ${Object.keys(wordMeta).length} metadata files`);

// 4. Replace placeholders in HTML
html = html.replace(
  'const SCENES = [];',
  scenesJS.replace('// Auto-generated by assemble.js — do not edit\n', '')
);

html = html.replace(
  'const AUDIO_DATA = {};',
  'const AUDIO_DATA = ' + JSON.stringify(audioData) + ';'
);

html = html.replace(
  'const WORD_META = {};',
  'const WORD_META = ' + JSON.stringify(wordMeta) + ';'
);

// 5. Write final HTML
fs.writeFileSync(HTML_OUT, html, 'utf-8');

const sizeMB = (Buffer.byteLength(html, 'utf-8') / 1024 / 1024).toFixed(2);
console.log(`\n✅ Built ${HTML_OUT}`);
console.log(`   Size: ${sizeMB} MB`);
